// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8XZ8SypH8ZkjhkB_Jfy_NSIj2u-amubM',
    appId: '1:798339020219:web:4bef4a9167ae94e829809e',
    messagingSenderId: '798339020219',
    projectId: 'women-entrepreneurship',
    authDomain: 'women-entrepreneurship.firebaseapp.com',
    databaseURL: 'https://women-entrepreneurship-default-rtdb.firebaseio.com',
    storageBucket: 'women-entrepreneurship.appspot.com',
    measurementId: 'G-51BHNVCQWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlZcadp9UgP8r2nv2A_g-VDCdVDoicU40',
    appId: '1:798339020219:android:b55a4dbf9e7035b329809e',
    messagingSenderId: '798339020219',
    projectId: 'women-entrepreneurship',
    databaseURL: 'https://women-entrepreneurship-default-rtdb.firebaseio.com',
    storageBucket: 'women-entrepreneurship.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLK8VLuJjbWK29tV-_aqsp-wUZmuTlPxs',
    appId: '1:798339020219:ios:ef13b86f90ff089b29809e',
    messagingSenderId: '798339020219',
    projectId: 'women-entrepreneurship',
    databaseURL: 'https://women-entrepreneurship-default-rtdb.firebaseio.com',
    storageBucket: 'women-entrepreneurship.appspot.com',
    androidClientId: '798339020219-ris9tmb6h1nadnb32p67p8431l7aqlt9.apps.googleusercontent.com',
    iosClientId: '798339020219-3qq57bl5ue5o8e3dad4ovpvjq6ro0ro8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wepProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLK8VLuJjbWK29tV-_aqsp-wUZmuTlPxs',
    appId: '1:798339020219:ios:1bbdad9014aab97529809e',
    messagingSenderId: '798339020219',
    projectId: 'women-entrepreneurship',
    databaseURL: 'https://women-entrepreneurship-default-rtdb.firebaseio.com',
    storageBucket: 'women-entrepreneurship.appspot.com',
    androidClientId: '798339020219-ris9tmb6h1nadnb32p67p8431l7aqlt9.apps.googleusercontent.com',
    iosClientId: '798339020219-fsadp9uqnqrfrvr6kp077br6t956h18f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wepProject.RunnerTests',
  );
}
